# CI de Nível 02 - Execução Agendada

# nome da pipeline
name: "N2 - Execução Agendada"

# gatilhos / triggers - regras de disparo
# gatilho manual = workflow_dispatch
# gatilho agendado = schedule

on:
  schedule:
    # cronograma de execução
    # 1 - minuto, 2 - hora, 3 dia do mês, 4 - mês, 5 - dia da semana
    #Roda a cada 30 minutos
    - cron: "*/30 * * * *"
jobs:
  #nome do job
  unidade:
    # maquina onde o job vai rodar
    runs-on: ubuntu-latest

    # passos do job
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalção do node
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x

      # instalação do mocha
      - name: Instalando mocha
        run: npm install -g mocha

      #   instalação das dependências
      - name: Instalando dependências
        run: mocha

      # executar os testes de unidade
      - name: Executando testes de unidade
        run: npx mocha
