# CI de Nível 04 - Pipeline Integrada ao Build do Código
# nome da pipeline
name: 'N4 -Execução Integrada'
# gatilhos / triggers - regras de disparo
# gatilho manual = workflow_dispatch
# gatilho agendado = schedule
# gatilho por conclusão de outra pipeline = workflow_run
on:
  workflow_dispatch:
#tarefas dentro da pipeline = jobs
jobs:
  #nome do job
  inspecao:
    # maquina onde o job vai rodar
    runs-on: ubuntu-latest
    # passos do job
    steps:
      # clone do projeto
      - uses: actions/checkout@v4
      # instalção do node
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      # instalação do mocha
      - name: Instalando mocha
        run: npm install -g mocha
      - name: Instalando dependências
        run: mocha
      - name: Inspeção de Código
        run: npx lint
  unidade:
    runs-on: ubuntu-latest
    needs: [inspecao]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Instalando mocha
        run: npm install -g mocha
      - name: Instalando dependências
        run: mocha
      - name: Rodando testes unitários
        run: npx mocha

      - name: Salvando relatórios de testes
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          path: ./mocha
          name: Relatório de Testes E2E
  deploy:
    runs-on: ubuntu-latest
    needs: [unidade]

    steps:
      - name: Simulação de deploy
        run: echo 'deploy sendo realizado...'
      - name: Simulação de Deploy
        run: echo 'Deploy sendo realizado...'